### ISSUE TITLE
acsm not login

### ISSUE THREAD

**Issue by jvaiguade** [SimoneDevkt/DockerAC#1]
Hi, 

I've tested this docker file and I can see acsm web but I can't login using normal  procedure 'docker compose up -d'

Invalid user name, but I've tried with the default password 'servermanager'

License is correct, no errors on docker logs...

Tried yet changing admin_password_override but no changes.

Any help?

Many thanks

**Comment by SimoneDevkt** [comment]
Hi, it seems like a problem with servermanager, not with docker, but probably you have fail the username, is 'admin' not 'root' o anything. 
(Without license servermanager premium can't start, it crash with an error)

**Comment by jvaiguade** [comment]
Yes, I've tried with user:admin and pass:servermanager but no luck.

I'm trying with the last version Assetto Corsa Server Manager Premium v2.3.0 and on the installation procedure you have tested  acsm_v2.1.6_linux-amd64.zip. I can't download that version :(

I will try a docker with only acsm, I will report here if I see it working

Many thanks

**Comment by SimoneDevkt** [comment]
i tried and i have the same problem with version > 2.2: acsm doasn't create the folder accounts and the admin.json file

A workaround can be go to servermanager\shared_store.json create accounts folder and put in a file admin.json whit this content

> {
>   "ID": "25f6bd2c-2681-48a5-a408-8d1825ef9a95",
>   "Created": "2023-01-07T00:24:49.215927367Z",
>   "Updated": "2023-01-07T00:25:40.401481297Z",
>   "Deleted": "0001-01-01T00:00:00Z",
>   "Name": "admin",
>   "Groups": {
>     "7949d043-1754-4e54-8b9b-6f5b71cb6ab3": "admin"
>   },
>   "DriverName": "",
>   "GUID": "",
>   "Team": "",
>   "PasswordHash": "",
>   "PasswordSalt": "",
>   "DefaultPassword": "servermanager",
>   "LastSeenVersion": "v1.3.4",
>   "HasSeenIntroPopup": false,
>   "Theme": "default",
>   "Group": "admin"
> }

I try it and i can login. 

I don't know why this file is not created, but i don't think is because of docker.

**Comment by jvaiguade** [comment]
Ok, tried this solution but only see Help button.

I've copied my current servermanager folder to DockerAC/servermanager and restarted docker and it worked

Maybe it's a folder permission issue

Many thanks again

**Comment by SimoneDevkt** [comment]
I asked this to acsm support and it will be fixed in next version. The official workaround is this
https://wiki.emperorservers.com/assetto-corsa-server-manager/troubleshooting-faq#i-cant-log-in-to-the-multi-server-manager-in-docker-after-a-first-time-setup-v217-v230
